// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_e5qmJm4MtrTnz1cUZaStVdCoKqBagQ',
    appId: '1:439341998850:web:8993fcd41bfef11a2f981b',
    messagingSenderId: '439341998850',
    projectId: 'trekky-8f8ca',
    authDomain: 'trekky-8f8ca.firebaseapp.com',
    storageBucket: 'trekky-8f8ca.firebasestorage.app',
    measurementId: 'G-ECVWY1DSRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaLt2FT-N4qRXLIah76JeljrBT8sPwgg',
    appId: '1:439341998850:android:6c85196f506a25352f981b',
    messagingSenderId: '439341998850',
    projectId: 'trekky-8f8ca',
    storageBucket: 'trekky-8f8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_vGquAWybV2X_Pl1KMJhGb6WYj0jqBA',
    appId: '1:439341998850:ios:879fea343eb9f5162f981b',
    messagingSenderId: '439341998850',
    projectId: 'trekky-8f8ca',
    storageBucket: 'trekky-8f8ca.firebasestorage.app',
    iosBundleId: 'com.example.trekkers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_vGquAWybV2X_Pl1KMJhGb6WYj0jqBA',
    appId: '1:439341998850:ios:879fea343eb9f5162f981b',
    messagingSenderId: '439341998850',
    projectId: 'trekky-8f8ca',
    storageBucket: 'trekky-8f8ca.firebasestorage.app',
    iosBundleId: 'com.example.trekkers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_e5qmJm4MtrTnz1cUZaStVdCoKqBagQ',
    appId: '1:439341998850:web:66bf5b10e2810fc72f981b',
    messagingSenderId: '439341998850',
    projectId: 'trekky-8f8ca',
    authDomain: 'trekky-8f8ca.firebaseapp.com',
    storageBucket: 'trekky-8f8ca.firebasestorage.app',
    measurementId: 'G-R4VZRK2J06',
  );
}
