// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUQJ45xWCEfpbyAVOMv_tTkH45NBoNYs',
    appId: '1:325137654893:web:63f2be3348c1cf309c8b64',
    messagingSenderId: '325137654893',
    projectId: 'pottery-house-33a71',
    authDomain: 'pottery-house-33a71.firebaseapp.com',
    storageBucket: 'pottery-house-33a71.appspot.com',
    measurementId: 'G-6233XV8ZER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsW8mxlzdRYScXa8eUMgyUvQrfydaAAY',
    appId: '1:325137654893:android:0d221c80687531699c8b64',
    messagingSenderId: '325137654893',
    projectId: 'pottery-house-33a71',
    storageBucket: 'pottery-house-33a71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTyvnnHcPur8jt8DF8jQpyqiiovj6Ky9M',
    appId: '1:325137654893:ios:98890c9790dbd2249c8b64',
    messagingSenderId: '325137654893',
    projectId: 'pottery-house-33a71',
    storageBucket: 'pottery-house-33a71.appspot.com',
    iosClientId: '325137654893-cr7fc9t7i4hkiol7rq18mafoa4osdrns.apps.googleusercontent.com',
    iosBundleId: 'com.example.trekkers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTyvnnHcPur8jt8DF8jQpyqiiovj6Ky9M',
    appId: '1:325137654893:ios:98890c9790dbd2249c8b64',
    messagingSenderId: '325137654893',
    projectId: 'pottery-house-33a71',
    storageBucket: 'pottery-house-33a71.appspot.com',
    iosClientId: '325137654893-cr7fc9t7i4hkiol7rq18mafoa4osdrns.apps.googleusercontent.com',
    iosBundleId: 'com.example.trekkers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYyJ52i9YQBMIwL24aa64MuDH5IHak6B4',
    appId: '1:325137654893:web:6f1c4c43c955c9ad9c8b64',
    messagingSenderId: '325137654893',
    projectId: 'pottery-house-33a71',
    authDomain: 'pottery-house-33a71.firebaseapp.com',
    storageBucket: 'pottery-house-33a71.appspot.com',
    measurementId: 'G-NHBQ9WVTNZ',
  );

}